import 'package:hive/hive.dart';

/// Represents a single scam analysis report generated by the SafeNet AI engine.
class AnalysisReport {
  final String id;
  final DateTime timestamp;
  final String scanType;
  final String content;
  final int riskScore;
  final int confidence;
  final String status;
  final String summary;
  final List<AnalysisReason> reasons;
  final List<String> recommendations;
  final ScamDna scamDna;
  bool isFavorite;

  AnalysisReport({
    required this.id,
    required this.timestamp,
    required this.scanType,
    required this.content,
    required this.riskScore,
    required this.confidence,
    required this.status,
    required this.summary,
    required this.reasons,
    required this.recommendations,
    required this.scamDna,
    this.isFavorite = false,
  });

  factory AnalysisReport.fromJson(Map<String, dynamic> json, {String? id, String? scanType, String? content}) {
    // Parse reasons: backend returns List<String>, mock returns List<Map>
    List<AnalysisReason> parsedReasons = [];
    final rawReasons = json['reasons'];
    if (rawReasons is List) {
      parsedReasons = rawReasons.map((item) {
        if (item is Map<String, dynamic>) {
          return AnalysisReason.fromJson(item);
        } else if (item is String) {
          // Backend returns plain strings — wrap them as a reason
          return AnalysisReason(
            title: item,
            description: item,
            severity: 'Medium',
          );
        }
        return AnalysisReason(title: '', description: '', severity: 'Low');
      }).toList();
    }

    // Parse recommendations: backend returns List<String>
    List<String> parsedRecs = [];
    final rawRecs = json['recommendations'];
    if (rawRecs is List) {
      parsedRecs = rawRecs.map((e) => e.toString()).toList();
    }

    // Derive status from riskScore if backend doesn't provide it
    final int riskScore = (json['risk_score'] ?? 0) as int;
    String derivedStatus = json['status'] ?? '';
    if (derivedStatus.isEmpty) {
      if (riskScore >= 75) {
        derivedStatus = 'High Risk';
      } else if (riskScore >= 40) {
        derivedStatus = 'Suspicious';
      } else {
        derivedStatus = 'Safe';
      }
    }

    // Derive summary if backend doesn't provide it
    String derivedSummary = json['summary'] ?? '';
    if (derivedSummary.isEmpty && parsedReasons.isNotEmpty) {
      derivedSummary = parsedReasons.first.description;
    }

    return AnalysisReport(
      id: id ?? json['id'] ?? DateTime.now().millisecondsSinceEpoch.toString(),
      timestamp: json['timestamp'] != null 
          ? DateTime.parse(json['timestamp']) 
          : DateTime.now(),
      scanType: scanType ?? json['scan_type'] ?? 'Text',
      content: content ?? json['content'] ?? '',
      riskScore: riskScore,
      confidence: json['confidence'] ?? riskScore,
      status: derivedStatus,
      summary: derivedSummary,
      reasons: parsedReasons,
      recommendations: parsedRecs,
      scamDna: ScamDna.fromJson(json['scam_dna'] ?? {}),
      isFavorite: json['is_favorite'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'timestamp': timestamp.toIso8601String(),
      'scan_type': scanType,
      'content': content,
      'risk_score': riskScore,
      'confidence': confidence,
      'status': status,
      'summary': summary,
      'reasons': reasons.map((r) => r.toJson()).toList(),
      'recommendations': recommendations,
      'scam_dna': scamDna.toJson(),
      'is_favorite': isFavorite,
    };
  }
}

/// Description of a specific security threat marker detected during analysis.
class AnalysisReason {
  final String title;
  final String description;
  final String severity; // Low, Medium, High, Critical

  AnalysisReason({
    required this.title,
    required this.description,
    required this.severity,
  });

  factory AnalysisReason.fromJson(Map<String, dynamic> json) {
    return AnalysisReason(
      title: json['title'] ?? '',
      description: json['description'] ?? '',
      severity: json['severity'] ?? 'Medium',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'description': description,
      'severity': severity,
    };
  }
}

/// Visual biometric levels indicating threat indicators.
class ScamDna {
  final int urgency;
  final int fear;
  final int money;
  final int identity;
  final int branding;

  ScamDna({
    required this.urgency,
    required this.fear,
    required this.money,
    required this.identity,
    required this.branding,
  });

  factory ScamDna.fromJson(Map<String, dynamic> json) {
    return ScamDna(
      urgency: json['urgency'] ?? 0,
      fear: json['fear'] ?? 0,
      money: json['money'] ?? 0,
      identity: json['identity'] ?? 0,
      branding: json['branding'] ?? 0,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'urgency': urgency,
      'fear': fear,
      'money': money,
      'identity': identity,
      'branding': branding,
    };
  }
}

// ==========================================
// CUSTOM HIVE ADAPTERS FOR LOCAL STORAGE
// ==========================================

class AnalysisReportAdapter extends TypeAdapter<AnalysisReport> {
  @override
  final int typeId = 0;

  @override
  AnalysisReport read(BinaryReader reader) {
    final id = reader.readString();
    final timestampMillis = reader.readInt();
    final scanType = reader.readString();
    final content = reader.readString();
    final riskScore = reader.readInt();
    final confidence = reader.readInt();
    final status = reader.readString();
    final summary = reader.readString();
    
    final reasonCount = reader.readInt();
    final reasons = List<AnalysisReason>.generate(reasonCount, (index) {
      return AnalysisReason(
        title: reader.readString(),
        description: reader.readString(),
        severity: reader.readString(),
      );
    });

    final recommendationCount = reader.readInt();
    final recommendations = List<String>.generate(recommendationCount, (index) {
      return reader.readString();
    });

    final scamDna = ScamDna(
      urgency: reader.readInt(),
      fear: reader.readInt(),
      money: reader.readInt(),
      identity: reader.readInt(),
      branding: reader.readInt(),
    );

    final isFavorite = reader.readBool();

    return AnalysisReport(
      id: id,
      timestamp: DateTime.fromMillisecondsSinceEpoch(timestampMillis),
      scanType: scanType,
      content: content,
      riskScore: riskScore,
      confidence: confidence,
      status: status,
      summary: summary,
      reasons: reasons,
      recommendations: recommendations,
      scamDna: scamDna,
      isFavorite: isFavorite,
    );
  }

  @override
  void write(BinaryWriter writer, AnalysisReport obj) {
    writer.writeString(obj.id);
    writer.writeInt(obj.timestamp.millisecondsSinceEpoch);
    writer.writeString(obj.scanType);
    writer.writeString(obj.content);
    writer.writeInt(obj.riskScore);
    writer.writeInt(obj.confidence);
    writer.writeString(obj.status);
    writer.writeString(obj.summary);
    
    writer.writeInt(obj.reasons.length);
    for (var reason in obj.reasons) {
      writer.writeString(reason.title);
      writer.writeString(reason.description);
      writer.writeString(reason.severity);
    }

    writer.writeInt(obj.recommendations.length);
    for (var rec in obj.recommendations) {
      writer.writeString(rec);
    }

    writer.writeInt(obj.scamDna.urgency);
    writer.writeInt(obj.scamDna.fear);
    writer.writeInt(obj.scamDna.money);
    writer.writeInt(obj.scamDna.identity);
    writer.writeInt(obj.scamDna.branding);

    writer.writeBool(obj.isFavorite);
  }
}
